# Generated by Django 3.2.15 on 2022-09-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_stu', models.IntegerField(primary_key=True, serialize=False)),
                ('name_stu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_sj', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name_sj', models.CharField(max_length=100)),
                ('sem_sj', models.IntegerField()),
                ('year_sj', models.IntegerField()),
                ('seat_sj', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sjApply', to='reg.subject')),
                ('id_stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stuApply', to='reg.student')),
            ],
        ),
    ]
